#!/bin/bash

# Reference:
# 1: https://wiki.archlinux.org/title/Pacman
# 2: https://stackoverflow.com/questions/1951506/add-a-new-element-to-an-array-without-specifying-the-index-in-bash
# 3: https://stackoverflow.com/questions/34567826/what-is-usage-in-shell-scripting


# Import the root check script
source ../utils/verify_root

# Instruction function to display help
# Ref - 3
Instruction() {
    echo "Instruction: $0 -f package_file_path"
    echo "  -f  Please type the package file to install after -f"
    exit 1
}

# Handle command line arguments using getopts
while getopts "f:" opt; do
  case ${opt} in
    f) package_file="$OPTARG" ;;
    *) Instruction ;;
  esac
done

# Check if the file argument is provided
if [[ -z "$package_file" ]]; then
    echo "Error: Package file not specified."
    Instruction
fi

# Check if the package file exists
if [[ ! -f "$package_file" ]]; then
    echo "Error: File '$package_file' not found."
    exit 1
fi

# Read each line from the package file into an array
# Ref - 2
packages=()
for package in $(cat "$package_file"); do
    packages+=("$package")
done

# Print the list of packages to install
echo "Packages to install: ${packages[@]}"

# Iterate over each package and install it 
# Ref - 1
for package in "${packages[@]}"; do
    if ! pacman -Qi "$package" &> /dev/null; then
        pacman -S "$package"
        echo "$package installed"
    else
        echo "$package is already installed"
    fi
done

