#!/bin/bash

# Import the root check script
source ../utils/verify_root

# # Get the user's home directory
# USER_HOME=$(eval echo "~$SUDO_USER")

# # Define paths relative to the user's home directory
# SCRIPT_DIR="$(realpath "$(dirname "$0")")"

# # Print process message
# echo "Creating symbolic links..."

# # Create symbolic links
# ln -sf "$SCRIPT_DIR/config" "$USER_HOME/.config"
# ln -sf "$SCRIPT_DIR/bin" "$USER_HOME/bin"
# ln -sf "$SCRIPT_DIR/home/bashrc" "$USER_HOME/.bashrc"

# # Print completion message
# echo "Symbolic links created successfully."

# Define directories
CURRENT_DIR="$(pwd)"
echo "Root directory is set to: $CURRENT_DIR"

# Ensure the ~/bin directory exists and create symbolic links for bin files
mkdir -p ~/bin
echo "Creating symbolic links in ~/bin"
ln -sf "$CURRENT_DIR/bin/sayhi" ~/bin/sayhi
ln -sf "$CURRENT_DIR/bin/install-fonts" ~/bin/install-fonts

# Ensure ~/.config/kak and ~/.config/tmux directories exist, then create symbolic links
echo "Creating ~/.config/kak directory"
mkdir -p ~/.config/kak
echo "Linking kakrc to ~/.config/kak/kakrc"
ln -sf "$CURRENT_DIR/config/kak/kakrc" ~/.config/kak/kakrc

echo "Creating ~/.config/tmux directory"
mkdir -p ~/.config/tmux
echo "Linking tmux.conf to ~/.config/tmux/tmux.conf"
ln -sf "$CURRENT_DIR/config/tmux/tmux.conf" ~/.config/tmux/tmux.conf

# Create a symbolic link for the bashrc file
echo "Linking bashrc to ~/.bashrc"
ln -sf "$CURRENT_DIR/home/bashrc" ~/.bashrc

echo "Symbolic links created successfully."

