#!/bin/bash

# Import the root check script
source ../utils/verify_root

# # Get the user's home directory
# USER_HOME=$(eval echo "~$SUDO_USER")

# # Define paths relative to the user's home directory
# SCRIPT_DIR="$(realpath "$(dirname "$0")")"

# # Print process message
# echo "Creating symbolic links..."

# # Create symbolic links
# ln -sf "$SCRIPT_DIR/config" "$USER_HOME/.config"
# ln -sf "$SCRIPT_DIR/bin" "$USER_HOME/bin"
# ln -sf "$SCRIPT_DIR/home/bashrc" "$USER_HOME/.bashrc"

# # Print completion message
# echo "Symbolic links created successfully."

# Define directories
CURRENT_DIR="$(pwd)"

# Create ~/bin and link files
mkdir -p ~/bin
ln -sf "$CURRENT_DIR/bin/sayhi" ~/bin/sayhi
ln -sf "$CURRENT_DIR/bin/install-fonts" ~/bin/install-fonts

# Create ~/.config and link config directories
mkdir -p ~/.config/kak
ln -sf "$CURRENT_DIR/config/kak/kakrc" ~/.config/kak/kakrc
mkdir -p ~/.config/tmux
ln -sf "$CURRENT_DIR/config/tmux/tmux.conf" ~/.config/tmux/tmux.conf

# Link bashrc file to ~/.bashrc
ln -sf "$CURRENT_DIR/home/bashrc" ~/.bashrc

echo "Symbolic links created successfully."

