#!/bin/bash

# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root (e.g., with 'sudo')."
    exit 1
fi

# Get the user's home directory
USER_HOME=$(eval echo "~$SUDO_USER")

# Define paths relative to the user's home directory
SCRIPT_DIR="$(realpath "$(dirname "$0")")"

echo "Setting up configuration files..."

# Symbolic links
ln -sf "$SCRIPT_DIR/config" "$USER_HOME/.config"
ln -sf "$SCRIPT_DIR/bin" "$USER_HOME/bin"
ln -sf "$SCRIPT_DIR/home/bashrc" "$USER_HOME/.bashrc"

echo "Configuration setup complete."
